### ISSUE TITLE
nwb_init_sphinx_extension_doc: Improve settings of default values

### ISSUE THREAD

**Issue by jcfr** [hdmf-dev/hdmf-docutils#35]
### Get metadata from namespace file, and better default values

If specified in namespace file, obtain author, version, project name, ... from it.  Additionally reasonable default could be set for few other parameters.

Doing so would simplify the invocation of `nwb_init_sphinx_extension_doc` from:

```
nwb_init_sphinx_extension_doc  \
             --project simulation_output \
             --author "Ben Dichter" \
             --version "0.2.0" \
             --release alpha \
             --output docs2 \
             --spec_dir /tmp/nwbext_simulation_output/spec \
             --namespace_filename simulation_output.namespace.yaml \
             --default_namespace simulation_output
```

to 

```
nwb_init_sphinx_extension_doc  \
             --output docs \
             --spec_dir /tmp/nwbext_simulation_output/spec \
             --namespace_filename simulation_output.namespace.yaml
```

where:
* `author` is the first name specified in the namespace file
* `project` and `default_namespace` are the namespace name
* `release` is initialized to `alpha` by default

The namespace file could also be automatically found.

### automatic updates of namespace file

On the other hand, if information like `author`, `version` are passed to `nwb_init_sphinx_extension_doc`, the namespace file could be updated if it doesn't already contain the info.

Last, if the info are already in the namespace file and the one passed in the command line contradict ... an exception  could be raised.

**Comment by oruebel** [comment]
This issue is being addressed by the ndx-template tool https://github.com/nwb-extensions/ndx-template
