### ISSUE TITLE
Package requires sphinx==1.6.5

### ISSUE THREAD

**Issue by t-b** [hdmf-dev/hdmf-docutils#47]
And this sphinx version is python2 only.

But if I look into https://github.com/NeurodataWithoutBorders/nwb-docutils/blob/02e94c831f91f03add180e4fbab6c396d85b3845/setup.py#L44 I would presume that it is python 3.5 or above.

**Comment by oruebel** [comment]
I think we forced the version at some point due to problems with sphinx and ReadTheDocs. I think it should be fine to update to a newer version.

**Comment by t-b** [comment]
@bendichter Is that now fixed?

**Comment by bendichter** [comment]
@t-b I'm not sure why this constraint was added to begin with but we've run tests with the latest and it works fine. Also this is the right time as we are EOLing py2. The adjustment has been merged.
