### ISSUE TITLE
sg_prototype test fails on remote CI

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf-docutils#53]
The sg_prototype test fails on Azure and GitHub CI but succeeds locally. It might be an issue with environments. The failure seems to have to do with Sphinx modules not being loaded correctly. 

@nicain @NileGraddis Is there still a need for sg_prototype.py?

It looks like it was developed during the April 2018 hackathon to allow rapid prototyping of Sphinx Gallery examples without rebuilding the full documentation, but it has not been used or updated anytime after that.
https://github.com/NeurodataWithoutBorders/pynwb/issues/414
https://github.com/NeurodataWithoutBorders/pynwb/pull/429
https://github.com/hdmf-dev/hdmf-docutils/issues/1

Can it be removed? Since it is not in use, as far as I can tell, let's comment out the test.

**Comment by oruebel** [comment]
@rly can this be closed or does sg_prototype.py need to be removed?
