### ISSUE TITLE
Show hierarchy depth in spec tables much more clearly

### ISSUE THREAD

**Issue by rly** [hdmf-dev/hdmf-docutils#75]
See https://github.com/NeurodataWithoutBorders/nwb-schema/issues/514

A quick fix is to change this line: 
https://github.com/hdmf-dev/hdmf-docutils/blob/96d381e7e84f7c5c526c2e6d69ae110d8f2c52d6/hdmf_docutils/doctools/renderrst.py#L601

to use `depth_char="----"` or `depth_char="└───"` or something

**Comment by oruebel** [comment]
If it's just changing the ``depth_char`` then there is no need to change that in the code. This is configured via the ``conf_doc_autogen.py`` configuration file as part of the sphinx docs.

**Comment by rly** [comment]
Good point. Here is the quick workaround by setting in `conf_doc_autogen.py`:
```
spec_table_depth_char = '---'
```
![image](https://user-images.githubusercontent.com/310197/164565394-6000c8ed-a08c-4456-a4e6-1864e1853d59.png)

Not the best but better, in my opinion. Even better would be to indent the first column of a nested row in a table, but that seems complicated to implement... This might be good enough for now. What do you think @bendichter @oruebel @CodyCBakerPhD ?

**Comment by CodyCBakerPhD** [comment]
Definitely communicates it better IMO. I agree a really nice indentation (maybe + alternate coloring for emphasis) would be best, but IDK how to do that either.

**Comment by oruebel** [comment]
Changing the ``spec_table_depth_char = '---'`` is fine with me. We should then also update the description of the notation here https://nwb-schema.readthedocs.io/en/latest/format_description.html#notation accordingly

> Even better would be to indent the first column of a nested row in a table

Creating nested row tables in sphinx is tricky (or more accurately, I don't know if Sphinx even supports this).

> maybe + alternate coloring for emphasis ...

Adding color to text should be feasible, but I'm not sure what the right color scheme is. If you just want color for the indentation marker, then you might even be able to do this directly by adding the appropriate rst commands in the ``spec_table_depth_char`` setting (but I'm not sure).
