### ISSUE TITLE
Setup GitHub test pipelines

### ISSUE THREAD

**Issue by oruebel** [hdmf-dev/hdmf-docutils#78]
As part of PRs we should run the following test pipelines:

1) Build the NWB schema docs to ensure changes are not affecting the docs
2) Build hdmf-common-schema docs

**Comment by mavaylon1** [comment]
@oruebel When we build readthedoc on PRs, that is usually from the corresponding repository and the readthedoc advanced settings. You want that build "preview" of whether it passed on each update on a PR for nwb-schema and hdmf-common-schema docs here as well? Correct?

**Comment by oruebel** [comment]
> You want that build "preview" of whether it passed on each update on a PR for nwb-schema and hdmf-common-schema docs here as well? Correct?

I'm not sure running this on readthedocs will work in this case, because this is a different repo and because the wb-schema and hdmf-common-schema docs are installing the hdmf-docutils from PIP. I think it may be easiest to have a GitHub action workflow to build the docs for these repos using the hdmf-docutils from the corresponding PR.
